FROM nginx:alpine

COPY . /usr/share/nginx/html

# Config de nginx para servir SPA correctamente
RUN echo 'server { \
    listen 80; \
    root /usr/share/nginx/html; \
    index index.html; \
    location / { \
        try_files $uri $uri/ /index.html; \
    } \
}' > /etc/nginx/conf.d/default.conf

EXPOSE 80
