[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:api]
command=uvicorn app.main:app --host 0.0.0.0 --port 8000
directory=/app
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:worker]
command=celery -A app.workers.celery_app worker --loglevel=info --concurrency=2
directory=/app
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:beat]
command=celery -A app.workers.celery_app beat --loglevel=info --scheduler app.workers.redis_scheduler:RedisAwareScheduler
directory=/app
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
